[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "chmod +x start.sh && ./start.sh"
healthcheckPath = "/health"
healthcheckTimeout = 120
healthcheckInterval = 10
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
initialDelaySeconds = 60

[deploy.volumes]
"/app/data" = "data"

[deploy.env]
PORT = "3000"
NODE_ENV = "production"
HOST = "0.0.0.0" 