[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "chmod +x start.sh && ./start.sh"
healthcheckPath = "/"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
initialDelaySeconds = 30

[deploy.volumes]
"/app/data" = "data" 